language: node_js
node_js:
  - "0.10"
  - "0.11"
services:
  - mongodb
before_script:
  - npm install -g mocha
  - npm install -g istanbul
after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/codacy-coverage/bin/codacy-coverage.js && rm -rf ./coverage
notifications:
  email:
    - jeffhann@gmail.com 
